<?php
## DATABASE CONFIGURATION ##
DEFINE("APP_HOST", "127.0.0.1");
DEFINE("APP_USERNAME", "root");
DEFINE("APP_PASSWORD", "");
DEFINE("APP_DBNAME", "berdikari");
DEFINE("APP_DOMAIN", "lokapala.website");
DEFINE("APP_PATH", "C:/xampp/htdocs/lokapalas/public_html/public/");
DEFINE("APP_DOMAIN_IMAGE", "lokapala.website");
DEFINE("APP_PATH_IMAGE", "admin/");
$config["webconfig"]["headline_count"] = 5;
$servername = "http://".APP_DOMAIN."/";
$pathbase              =  APP_PATH;
$servernamemedia       = $servername.'public/';
$servernameimg = "http://".APP_DOMAIN_IMAGE."/";
$pathbaseimg              =  APP_PATH_IMAGE;
$servernamemediaimg       = $servernameimg.'admin/';
$dateformat = "Y-m-d H:i";
$config["webconfig"]["lokapala_template"] = $servernamemedia."template/lokapala_template/";
$config["webconfig"]["pagename-home"] = "Home";
$config["webconfig"]["limitberita-home"] = 6;
$config["webconfig"]["limit_berita"] = 9;
$config["webconfig"]["limitanalisis-home"] = 4;
$config["webconfig"]["limit_analisis"] = 11;
$config["webconfig"]["limitvideo-home"] = 7;
$config["webconfig"]["limit_video"] = 7;
$config["webconfig"]["limitgrafik-home"] = 7;
$config["webconfig"]["limit_grafik"] = 7;
$config["webconfig"]["limitterpopuler_home"] = 5;
$config["webconfig"]["interval"] = 90;
$config["webconfig"]["category-id-berita"] = "50";
$config["webconfig"]["category-id-grafik"] = "51";
$config["webconfig"]["category-id-analisis"] = "3303";
$config["webconfig"]["category-id-video"] = "52";
$config['webconfig']["limit_headline_home_new"] = 3;
$config['webconfig']["limitterpopuler_home"] = 5;
$config['webconfig']["fb_lokapala"] = 'https://www.facebook.com/pg/lokapala.id/';
$config['webconfig']["twitter_lokapala"] = '';
$config['webconfig']["google_lokapala"] = 'https://plus.google.com/u/3/';
$config["webconfig"]["media-server-images-thumb"] = $servernamemediaimg."pic/resize/";
$config["webconfig"]["media-path-images-thumb"] = $pathbaseimg."pic/resize/";
$config["webconfig"]["media-server-images-original"] = $servernamemediaimg."pic/original/";
$config["webconfig"]["media-path-images-original"] = $pathbaseimg."pic/original/";